[package]
name = "seaside"
version = "1.2.0"
authors = ["RosieTheGhostie"]
edition = "2021"

[profile.release]
opt-level = 3
debug = false
strip = true
debug-assertions = false
overflow-checks = true
incremental = true

[dependencies]
anyhow = "1.0"
directories = "5.0"
seaside-assembler = { version = "0.1", path = "crates/seaside-assembler" }
seaside-bitflags-addons = { version = "0.1", path = "crates/seaside-bitflags-addons" }
seaside-config = { version = "0.1", path = "crates/seaside-config" }
seaside-constants = { version = "0.1", path = "crates/seaside-constants" }
seaside-disassembler = { version = "0.1", path = "crates/seaside-disassembler" }
seaside-error = { version = "0.1", path = "crates/seaside-error" }
seaside-int-utils = { version = "0.3", path = "crates/seaside-int-utils" }
seaside-interpreter = { version = "0.1", path = "crates/seaside-interpreter" }
seaside-type-aliases = { version = "0.1", path = "crates/seaside-type-aliases" }
toml = "0.8"

[dependencies.clap]
version = "4.5"
features = ["cargo", "derive"]

[dependencies.minimal-logging]
version = "0.5"
features = ["full"]
git = "https://github.com/RosieTheGhostie/minimal-logging.git"
