[package]
name = "seaside"
version = "0.1.0"
authors = ["RosieTheGhostie"]
edition = "2021"

[dependencies]
bitflags = "2.6"
convert_case = "0.6"
num-derive = "0.4"
num-traits = "0.2"
rand = "0.8"
semver = "1.0"
toml = "0.8"
walkdir = "2.5"

[dependencies.clap]
version = "4.5"
features = ["cargo", "derive"]

[dependencies.minimal-logging]
version = "0.4"
features = ["full"]
git = "https://github.com/RosieTheGhostie/minimal-logging.git"

[dependencies.serde]
version = "1.0"
features = ["derive"]
