[package]
name = "seaside-v2"
version = "0.1.0"
authors = ["RosieTheGhostie"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bitflags = "2.6"
convert_case = "0.6"
num-traits = "0.2"
toml = "0.8"
walkdir = "2.5"

[dependencies.clap]
version = "4.5"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]
