[package]
name = "seaside"
version = "1.2.0"
authors = ["RosieTheGhostie"]
edition = "2021"

[profile.release]
opt-level = 3
debug = false
strip = true
debug-assertions = false
overflow-checks = true
incremental = true

[dependencies]
bitflags = "2.6"
console = "0.15"
convert_case = "0.6"
logos = "0.15"
num-derive = "0.4"
num-traits = "0.2"
rand = "0.8"
semver = "1.0"
toml = "0.8"

[dependencies.clap]
version = "4.5"
features = ["cargo", "derive"]

[dependencies.minimal-logging]
version = "0.5"
features = ["full"]
git = "https://github.com/RosieTheGhostie/minimal-logging.git"

[dependencies.serde]
version = "1.0"
features = ["derive"]
