version = "1.2.0"
endian = "little"
project_directory_is_cwd = true

[features]
kernel_space_accessible = true
self_modifying_code = false
delay_slot = false
freeable_heap_allocations = true
show_crash_handler = true

[features.assembler]
pseudo_instructions = false
directives = "recommended"

[features.syscalls]
print_int = 1
print_float = 2
print_double = 3
print_string = 4
print_char = 11
print_hex = 34
print_bin = 35
print_uint = 36
read_int = 5
read_float = 6
read_double = 7
read_string = 8
read_char = 12
open_file = 13
read_file = 14
write_file = 15
close_file = 16
sbrk = 9
exit = 10
exit2 = 17
time = 30
sleep = 32
midi_out = 31
midi_out_sync = 33
set_seed = 40
rand_int = 41
rand_int_range = 42
rand_float = 43
rand_double = 44
confirm_dialog = 50
input_dialog_int = 51
input_dialog_float = 52
input_dialog_double = 53
input_dialog_string = 54
message_dialog = 55
message_dialog_int = 56
message_dialog_float = 57
message_dialog_double = 58
message_dialog_string = 59

[memory_map]
exception_handler = 0x80000180

[memory_map.user_space]
base = 0x00000000
limit = 0x7fffffff

[memory_map.kernel_space]
base = 0x80000000
limit = 0xffffffff

[memory_map.segments]

[memory_map.segments.text]
base = 0x00400000
limit = 0x0ffffffc
allocate = 0x800000 # 8 MiB

[memory_map.segments.extern]
base = 0x10000000
limit = 0x1000ffff
allocate = 0x10000 # 64 KiB

[memory_map.segments.data]
base = 0x10010000
limit = 0x1003ffff
allocate = 0x30000 # 192 KiB

[memory_map.segments.runtime_data]
base = 0x10040000
limit = 0x7fffffff
heap_size = 0x20000   # 128 KiB
stack_size = 0x400000 # 4 MiB

[memory_map.segments.ktext]
base = 0x80000000
limit = 0x8fffffff
allocate = 0x100000 # 1 MiB

[memory_map.segments.kdata]
base = 0x90000000
limit = 0xfffeffff
allocate = 0x100000 # 1 MiB

[memory_map.segments.mmio]
base = 0xffff0000
limit = 0xffffffff
allocate = 0x1000  # 4 KiB

[register_defaults]

[register_defaults.general_purpose]
gp = 0x10008000
sp = 0x7fffeffc

[register_defaults.coprocessor_0]
status = 0x0000ff11
