[package]
name = "seaside-assembler"
description = "The MIPS32 assembler for seaside"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ariadne = "0.6.0"
const_format = { version = "0.2.34", features = ["fmt"] }
logos = "0.16.1"
seaside-config = { version = "*", path = "../config" }
seaside-executable = { version = "0.1.0", path = "../executable" }
seaside-type-aliases = { version = "*", path = "../type-aliases" }
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.12"

[dependencies.seaside-constants]
version = "*"
path = "../constants"
features = ["register", "number-format", "opcodes", "static-segment"]

[dependencies.seaside-error]
version = "*"
path = "../error"
features = ["rich"]

[dependencies.seaside-int-utils]
version = "*"
path = "../int-utils"
features = ["endian"]
