[package]
name = "seaside-assembler"
description = "The MIPS32 assembler for seaside"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ariadne = "0.6.0"
const_format = { version = "0.2.34", features = ["fmt"] }
logos = "0.16.1"
seaside-config = { version = "*", path = "../config" }
seaside-core = { version = "0.1.0", path = "../core" }
seaside-executable = { version = "0.1.0", path = "../executable" }
seaside-rich-error = { version = "0.2.0", path = "../rich-error" }
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.12"
