[package]
name = "seaside-disassembler"
description = "The MIPS32 disassembler for seaside"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
num-traits = "0.2"
seaside-core = { version = "0.1.0", path = "../core" }

[features]
default = ["fields", "disassembler"]
full = ["fields", "disassembler"]

fields = []
disassembler = ["fields"]
