[package]
name = "seaside-disassembler"
description = "The MIPS32 disassembler for seaside"
version = "0.1.0"
authors = ["RosieTheGhostie <rosetheghost.dev@gmail.com>"]
edition = "2024"

[dependencies]
num-traits = "0.2"
seaside-type-aliases = { version = "*", path = "../type-aliases" }

[dependencies.seaside-constants]
version = "*"
path = "../constants"
features = ["instruction-format"]

[dependencies.seaside-int-utils]
version = "*"
path = "../int-utils"
features = ["sign-extend"]

[features]
default = ["fields", "disassembler"]
full = ["fields", "disassembler"]

fields = []
disassembler = ["fields"]
