[package]
name = "seaside-type-aliases"
description = "A handful of type aliases for seaside"
version = "0.1.0"
authors = ["RosieTheGhostie"]
edition = "2021"

[lib]
crate-type = ["lib"]
path = "src/lib.rs"
