[package]
name = "seaside-executable"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
bitflags = { version = "2.10.0", features = ["serde"] }
rmp-serde = "1.3.1"
seaside-core = { version = "0.1.0", path = "../core", features = [
  "serde",
  "validator",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
thiserror = "2.0.18"
validator = { version = "0.20.0", features = ["derive"] }
