[package]
name = "seaside-address-range"
version = "0.1.0"
edition = "2024"

[dependencies]
seaside-type-aliases = { version = "*", path = "../type-aliases" }
serde = { version = "1.0.219", optional = true }

[dependencies.seaside-int-utils]
version = "*"
path = "../int-utils"
optional = true

[features]
sized = ["serde?/derive"]

default = ["sized"]
full = ["seaside-int-utils", "serde", "sized"]
