[package]
name = "seaside-address-range"
description = "Specialized address-related ranges for seaside"
version = "0.1.0"
authors = ["RosieTheGhostie <rosetheghost.dev@gmail.com>"]
edition = "2024"

[dependencies]
seaside-type-aliases = { version = "*", path = "../type-aliases" }
serde = { version = "1.0.219", optional = true }

[features]
default = []
full = ["serde"]
