[package]
name = "seaside-interpreter"
description = "The MIPS32 interpreter for seaside"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.101"
bitfields = "1.0.2"
console = "0.16.2"
num-traits = "0.2"
rand = "0.10.0"
seaside-config = { version = "*", path = "../config" }
seaside-core = { version = "0.1.0", path = "../core" }
seaside-executable = { version = "0.1.0", path = "../executable" }
strum = "0.27.2"
thiserror = "2.0.18"

[dependencies.minimal-logging]
version = "0.5"
git = "https://github.com/RosieTheGhostie/minimal-logging.git"
features = ["full"]

[dependencies.seaside-disassembler]
version = "*"
path = "../disassembler"
default-features = false
features = ["fields"]
