[package]
name = "seaside-interpreter"
description = "The MIPS32 interpreter for seaside"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.101"
console = "0.16.2"
num-traits = "0.2"
rand = "0.9.2"
seaside-config = { version = "*", path = "../config" }
seaside-error = { version = "*", path = "../error" }
seaside-executable = { version = "0.1.0", path = "../executable" }
seaside-type-aliases = { version = "*", path = "../type-aliases" }
strum = "0.27.2"
thiserror = "2.0.18"

[dependencies.minimal-logging]
version = "0.5"
git = "https://github.com/RosieTheGhostie/minimal-logging.git"
features = ["full"]

[dependencies.seaside-constants]
version = "*"
path = "../constants"
features = ["number-format", "register", "services"]

[dependencies.seaside-int-utils]
version = "*"
path = "../int-utils"
features = ["byte-stream", "endian"]

[dependencies.seaside-disassembler]
version = "*"
path = "../disassembler"
default-features = false
features = ["fields"]
